import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createDeposition, depositionDirectory, resolveDepositionAudio, scanDepositions, _testing } from "../server/deposition-store.mjs";

function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"depo-store-")),uploadId=crypto.randomUUID(),directory=path.join(root,"data","audio-intake",uploadId);fs.mkdirSync(directory,{recursive:true});const bytes=Buffer.from("audited audio"),sha256=crypto.createHash("sha256").update(bytes).digest("hex");fs.writeFileSync(path.join(directory,"original.wav"),bytes);fs.writeFileSync(path.join(directory,"audit.json"),JSON.stringify({schemaVersion:"3.0.0",uploadId,originalName:"recording.wav",selectedSource:"original",selectedDerivativeOperationId:null,storage:{original:{key:`audio-intake/${uploadId}/original.wav`,sha256,bytes:bytes.length,immutable:true},derivatives:[]},history:[]}));return{root,uploadId,bytes}}

test("deposition store supports multiple depositions within one reporter and cause",t=>{const value=fixture(),storageRoot=path.join(value.root,"depos"),options={storageRoot},common={caseStyle:"Smith v. Jones",courtReporterName:"Brenda Miah",causeNumber:"2026-CV-00123",audioIntakeIds:[value.uploadId],keyterms:["Smith"]};t.after(()=>fs.rmSync(value.root,{recursive:true,force:true}));const first=createDeposition(value.root,{deposition:{...common,id:"DEP-20260813-ABCDE",witness:"Alex Smith",depositionDate:"2026-08-13"},artifacts:{notice:{name:"notice.pdf",base64:Buffer.from("notice").toString("base64")}}},options),second=createDeposition(value.root,{deposition:{...common,id:"DEP-20260814-FGHIJ",witness:"Jordan Jones",depositionDate:"2026-08-14"}},options);assert.equal(first.storagePath,"miah_b/2026-cv-00123/smith_alex_2026-08-13");assert.equal(second.storagePath,"miah_b/2026-cv-00123/jones_jordan_2026-08-14");assert.equal(first.audio[0].sha256,crypto.createHash("sha256").update(value.bytes).digest("hex"));assert.ok(fs.existsSync(path.join(storageRoot,...first.storagePath.split("/"),"deposition.json")));assert.ok(fs.existsSync(path.join(storageRoot,...first.storagePath.split("/"),"intake","canonical-deposition-record.json")));assert.equal(first.canonicalData.recordType,"CANONICAL_DEPOSITION_DATA_RECORD");assert.ok(fs.existsSync(path.join(storageRoot,...second.storagePath.split("/"),"deposition.json")));assert.deepEqual(scanDepositions(value.root,options).depositions.map(item=>item.id).sort(),[first.id,second.id].sort());assert.deepEqual(fs.readFileSync(resolveDepositionAudio(value.root,first.id,0,options).file),value.bytes)});

test("live depositions are persisted as scheduled before any audio exists",t=>{const value=fixture(),storageRoot=path.join(value.root,"depos"),options={storageRoot};t.after(()=>fs.rmSync(value.root,{recursive:true,force:true}));const saved=createDeposition(value.root,{deposition:{id:"DEP-20260819-LIVE1",caseStyle:"Smith v. Jones",witness:"Alex Smith",courtReporterName:"Brenda Miah",causeNumber:"2026-CV-00123",depositionDate:"2026-08-21",creationMode:"live",workflowStatus:"scheduled"},artifacts:{notice:{name:"notice.pdf",base64:Buffer.from("notice").toString("base64")}}},options);assert.equal(saved.creationMode,"live");assert.equal(saved.workflowStatus,"scheduled");assert.deepEqual(saved.audio,[]);assert.equal(saved.schemaVersion,"1.2.0")});

test("reporter folder supports natural and last-name-first names",()=>{assert.equal(_testing.reporterFolder("Brenda Miah"),"miah_b");assert.equal(_testing.reporterFolder("Miah, Brenda"),"miah_b");assert.equal(_testing.reporterFolder("Brenda Miah, Jr."),"miah_b")});

test("storage identity accepts manual cause number and requires core filing fields",()=>{assert.equal(_testing.causeFolder({causeNumber:"25-CV-00598-OLG",ufmData:{cause_number:"wrong"}}),"25-cv-00598-olg");assert.equal(_testing.depositionFolder({witness:"Heath Thomas",depositionDate:"2026-04-30"}),"thomas_heath_2026-04-30");assert.throws(()=>_testing.reporterFolder(""),/Court reporter is required/);assert.throws(()=>_testing.causeFolder({ufmData:{}}),/Cause number is required/)});

test("Windows directory commit retries transient file locks",()=>{let calls=0,waits=0;_testing.commitDirectory("staging","final",{rename:()=>{calls++;if(calls<3)throw Object.assign(new Error("locked"),{code:"EPERM"})},wait:()=>{waits++},attempts:3});assert.equal(calls,3);assert.equal(waits,2)});

test("directory commit does not retry non-transient failures",()=>{let calls=0;assert.throws(()=>_testing.commitDirectory("staging","final",{rename:()=>{calls++;throw Object.assign(new Error("exists"),{code:"EEXIST"})},wait:()=>{},attempts:20}),/exists/);assert.equal(calls,1)});

test("exhausted Windows rename has a distinguishable error",()=>{const waits=[];assert.throws(()=>_testing.commitDirectory("staging","final",{rename:()=>{throw Object.assign(new Error("locked"),{code:"EBUSY"})},wait:value=>waits.push(value),attempts:3,delayBaseMs:10}),error=>error.code==="DEPOSITION_COMMIT_BLOCKED"&&/after 3 attempts/.test(error.message));assert.deepEqual(waits,[10,20])});

test("scanner reports orphaned and malformed deposition folders",t=>{const value=fixture(),storageRoot=path.join(value.root,"depos"),options={storageRoot};t.after(()=>fs.rmSync(value.root,{recursive:true,force:true}));fs.mkdirSync(path.join(storageRoot,"miah_b","cause","deposition_a"),{recursive:true});fs.mkdirSync(path.join(storageRoot,"miah_b","cause","deposition_b"),{recursive:true});fs.writeFileSync(path.join(storageRoot,"miah_b","cause","deposition_b","deposition.json"),"not json");const issues=scanDepositions(value.root,options).issues;assert.equal(issues.find(item=>item.folder.endsWith("deposition_a")).code,"ORPHANED_FOLDER");assert.equal(issues.find(item=>item.folder.endsWith("deposition_b")).code,"MALFORMED_DEPOSITION")});

test("invalid IDs and traversal are rejected before filesystem access",()=>{assert.throws(()=>depositionDirectory("C:/safe","../outside",{storageRoot:"C:/safe/depos"}),/Invalid deposition ID/);assert.throws(()=>depositionDirectory("C:/safe","DEP-20260813-AAAAA/../../x",{storageRoot:"C:/safe/depos"}),/Invalid deposition ID/)});
