import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import {armPreflight,confirmPlayback,createPreflight,runTestCapture,_testing,PREFLIGHT_STATES} from "../server/live-preflight.mjs";
const sources=[{id:"ch1",deviceId:"mic-a",role:"LOCAL"},{id:"ch2",deviceId:"mix-a",role:"REMOTE"}];
test("preflight lifecycle is explicit and ordered",()=>assert.deepEqual(PREFLIGHT_STATES,["NOT_TESTED","TEST_CAPTURED","PLAYBACK_CONFIRMED","ARMED"]));
test("changing any selected device invalidates the tested signature",()=>{const before=_testing.signature(sources),after=_testing.signature([{...sources[0],deviceId:"mic-b"},sources[1]]);assert.notEqual(before,after)});
test("roles and arbitrary N-channel identity contribute to readiness",()=>{assert.notEqual(_testing.signature(sources),_testing.signature([...sources,{id:"ch3",deviceId:"aux",role:"AUX"}]))});
function fixture(){const storageRoot=fs.mkdtempSync(path.join(os.tmpdir(),"depo-preflight-")),folder=path.join(storageRoot,"r","c","w");fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,"deposition.json"),JSON.stringify({id:"DEP-20260818-PF002",caseStyle:"A",witness:"B"}));return{storageRoot,folder}}
test("simulated N-channel signal completes the local-only readiness lifecycle",async()=>{const {storageRoot}=fixture(),depositionId="DEP-20260818-PF002",created=createPreflight(process.cwd(),{depositionId,storageRoot,sources});const tested=await runTestCapture(process.cwd(),{depositionId,preflightId:created.preflightId,storageRoot,captureFn:async(_device,file)=>{fs.writeFileSync(file,Buffer.alloc(128));return{rmsDb:-28,peakDb:-4}}});assert.equal(tested.state,"TEST_CAPTURED");assert.equal(tested.checks.audioReceived,true);assert.equal(confirmPlayback(process.cwd(),{depositionId,preflightId:created.preflightId,storageRoot}).state,"PLAYBACK_CONFIRMED");assert.equal(armPreflight(process.cwd(),{depositionId,preflightId:created.preflightId,storageRoot,minFreeBytes:1}).state,"ARMED");fs.rmSync(storageRoot,{recursive:true,force:true})});
test("no-signal on any independent source prevents arming",async()=>{const {storageRoot}=fixture(),depositionId="DEP-20260818-PF002",created=createPreflight(process.cwd(),{depositionId,storageRoot,sources});await runTestCapture(process.cwd(),{depositionId,preflightId:created.preflightId,storageRoot,captureFn:async(device,file)=>{fs.writeFileSync(file,Buffer.alloc(128));return device==="mix-a"?{rmsDb:-90,peakDb:-80}:{rmsDb:-30,peakDb:-5}}});confirmPlayback(process.cwd(),{depositionId,preflightId:created.preflightId,storageRoot});assert.throws(()=>armPreflight(process.cwd(),{depositionId,preflightId:created.preflightId,storageRoot,minFreeBytes:1}),/Every source/);fs.rmSync(storageRoot,{recursive:true,force:true})});
