"use client";
import { useState } from "react";
import type { AudioProfile } from "./IntakeScreen";
const API="http://127.0.0.1:4317";
type Props={profile:AudioProfile;keyterms:string[];onProfile:(profile:AudioProfile)=>void};
export default function AudioReviewCard({profile,keyterms,onProfile}:Props){
 const [expanded,setExpanded]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[transcript,setTranscript]=useState(""),[reference,setReference]=useState(""),[comparison,setComparison]=useState<any>(null);
 async function post(endpoint:string,payload:unknown){const response=await fetch(`${API}${endpoint}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Request failed.");return result}
 async function select(source:"original"|"processed"){setBusy("select");setError("");try{onProfile(await post("/api/audio/select",{uploadId:profile.uploadId,source}))}catch(e){setError(e instanceof Error?e.message:"Selection failed.")}finally{setBusy("")}}
 async function transcribe(){setBusy("transcribe");setError("");try{const result=await post("/api/audio/transcribe",{uploadId:profile.uploadId,source:profile.selectedSource,keyterms});setTranscript(result.transcript||"");setExpanded(true)}catch(e){setError(e instanceof Error?e.message:"Transcription failed.")}finally{setBusy("")}}
 async function compare(){setBusy("compare");setError("");try{setComparison(await post("/api/transcript/compare",{uploadId:profile.uploadId,source:profile.selectedSource,reference,hypothesis:transcript,criticalTerms:keyterms}))}catch(e){setError(e instanceof Error?e.message:"Comparison failed.")}finally{setBusy("")}}
 const findings=Object.entries(profile.findings||{}).filter(([,value])=>value.detected===true).map(([name])=>name),processedAvailable=profile.storage.derivatives.length>0,media=profile.media;
 return <div className="audio-review-card"><div className="audio-review-summary"><div><span className={`route-badge route-${profile.recommendation?.route||"review"}`}>{profile.status==="analysis-failed"?"Analysis failed":profile.recommendation?.route||"Review"}</span><strong>{findings.length?findings.join(" · "):"No validated concern"}</strong><small>{profile.recommendation?.reason||"The immutable original was preserved; use it until analysis succeeds."}</small></div><button type="button" onClick={()=>setExpanded(v=>!v)}>{expanded?"Hide details":"Review audio"}</button></div>{expanded&&<div className="audio-review-details">
 <dl><div><dt>Original SHA-256</dt><dd title={profile.storage.original.sha256}>{profile.storage.original.sha256.slice(0,16)}…</dd></div><div><dt>Status</dt><dd>{profile.status}</dd></div>{media&&<><div><dt>Duration</dt><dd>{media.durationSeconds.toFixed(1)} sec</dd></div><div><dt>Format</dt><dd>{media.codec} · {media.sampleRate} Hz · {media.channels} ch</dd></div></>}</dl>
 <fieldset><legend>Audio sent to Deepgram</legend><label><input type="radio" checked={profile.selectedSource==="original"} onChange={()=>select("original")} disabled={Boolean(busy)}/> Untouched original</label><label className={!processedAvailable?"disabled":""}><input type="radio" checked={profile.selectedSource==="processed"} onChange={()=>select("processed")} disabled={!processedAvailable||Boolean(busy)}/> Candidate derivative {!processedAvailable&&"(not created)"}</label></fieldset>
 {profile.automaticSelection&&<p className="automatic-selection"><b>Automatic selection: {profile.automaticSelection.winner}</b> · {profile.automaticSelection.reason}{!profile.automaticSelection.measuredWer&&" This is an ASR quality estimate, not measured WER."}</p>}{processedAvailable&&!profile.automaticSelection&&profile.selectionBasis==="safety-default"&&<p className="candidate-notice">The candidate is not selected automatically until the ASR comparison completes.</p>}<div className="audio-review-actions"><button type="button" onClick={transcribe} disabled={Boolean(busy)}>{busy==="transcribe"?"Transcribing…":"Transcribe selected audio"}</button></div>
 {transcript&&<><label className="transcript-field">Deepgram transcript<textarea rows={6} value={transcript} onChange={e=>setTranscript(e.target.value)}/></label><label className="transcript-field">Verified reference transcript<textarea rows={6} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Paste the court-reporter-verified excerpt."/></label><button className="quality-button" type="button" onClick={compare} disabled={!reference||Boolean(busy)}>{busy==="compare"?"Comparing…":"Calculate WER and critical legal errors"}</button></>}
 {comparison&&<div className="quality-results"><span><b>{(comparison.wer*100).toFixed(2)}%</b> WER</span><span><b>{comparison.criticalLegalErrorRate===null?"N/A":`${(comparison.criticalLegalErrorRate*100).toFixed(2)}%`}</b> Critical legal error rate</span><span><b>{comparison.errors}</b> Total word errors</span></div>}<details><summary>Findings, provenance, and RX audit</summary><pre>{JSON.stringify({schemaVersion:profile.schemaVersion,measurements:profile.measurements,findings:profile.findings,storage:profile.storage,rx:profile.rx,history:profile.history},null,2)}</pre></details>{error&&<p className="analysis-error" role="alert">{error}</p>}</div>}</div>
}
