"use client";
import { useState } from "react";
import type { AudioProfile } from "./IntakeScreen";
import { LOCAL_API_BASE_URL as API } from "./api-client";
const FINDING_LABELS:Record<string,string>={lowLevel:"Low recording level",clipping:"Possible clipping",lowFrequencyEnergy:"Low-frequency noise",unevenLevels:"Uneven volume levels",lineHum:"Electrical hum",impulses:"Clicks or impulses",echo:"Room echo",uncertain:"Analysis uncertainty"};
type Props={profile:AudioProfile;keyterms:string[];onProfile:(profile:AudioProfile)=>void};
export default function AudioReviewCard({profile,onProfile}:Props){
 const [expanded,setExpanded]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState("");
 async function post(endpoint:string,payload:unknown){const response=await fetch(`${API}${endpoint}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Request failed.");return result}
 const processingDerivatives=profile.storage.derivatives.filter(item=>item.kind!=="deepgram-compatibility"),selectedDerivative=processingDerivatives.at(-1);
 async function select(source:"original"|"processed"){setBusy("select");setError("");try{onProfile(await post("/api/audio/select",{uploadId:profile.uploadId,source,derivativeOperationId:source==="processed"?selectedDerivative?.operationId:null}))}catch(e){setError(e instanceof Error?e.message:"Selection failed.")}finally{setBusy("")}}
 const findings=Object.entries(profile.findings||{}).filter(([name,value])=>value.detected===true&&name!=="clean").map(([name])=>FINDING_LABELS[name]||name),processedAvailable=processingDerivatives.length>0,media=profile.media,isManualRx=profile.selectionBasis==="manual-rx-processing";
 return <div className="audio-review-card"><div className="audio-review-summary"><div><span className={`route-badge route-${isManualRx?"processed":profile.recommendation?.route||"review"}`}>{isManualRx?"RX processed":profile.status==="analysis-failed"?"Analysis failed":profile.recommendation?.route||"Review"}</span><strong>{isManualRx?`${selectedDerivative?.module||"RX module"} applied`:findings.length?findings.join(" · "):"No validated concern"}</strong><small>{isManualRx?"The lossless processed derivative is selected. Original defects remain preserved in the RX audit.":profile.recommendation?.reason||"The immutable original was preserved; use it until analysis succeeds."}</small></div><button type="button" onClick={()=>setExpanded(v=>!v)}>{expanded?"Hide details":"Review audio"}</button></div>{expanded&&<div className="audio-review-details">
 <dl><div><dt>Original SHA-256</dt><dd title={profile.storage.original.sha256}>{profile.storage.original.sha256.slice(0,16)}…</dd></div><div><dt>Status</dt><dd>{profile.status}</dd></div>{media&&<><div><dt>Duration</dt><dd>{media.durationSeconds.toFixed(1)} sec</dd></div><div><dt>Format</dt><dd>{media.codec} · {media.sampleRate} Hz · {media.channels} ch</dd></div></>}</dl>
 <fieldset><legend>Audio sent to Deepgram</legend><label><input type="radio" checked={profile.selectedSource==="original"} onChange={()=>select("original")} disabled={Boolean(busy)}/> As uploaded</label><label className={!processedAvailable?"disabled":""}><input type="radio" checked={profile.selectedSource==="processed"} onChange={()=>select("processed")} disabled={!processedAvailable||Boolean(busy)}/> Candidate derivative {!processedAvailable&&"(not created)"}</label></fieldset>
 {profile.automaticSelection&&<p className="automatic-selection"><b>Automatic selection: {profile.automaticSelection.winner}</b> · {profile.automaticSelection.reason}{!profile.automaticSelection.measuredWer&&" This is an ASR quality estimate, not measured WER."}</p>}{processedAvailable&&!profile.automaticSelection&&profile.selectionBasis==="safety-default"&&<p className="candidate-notice">The original remains selected unless you explicitly choose the processed candidate.</p>}<p className="analysis-note">Transcription is available after the deposition is created, when the server can load its authoritative keyterm record.</p>
 <details><summary>Findings, provenance, and RX audit</summary><pre>{JSON.stringify({schemaVersion:profile.schemaVersion,measurements:profile.measurements,findings:profile.findings,storage:profile.storage,rx:profile.rx,history:profile.history},null,2)}</pre></details>{error&&<p className="analysis-error" role="alert">{error}</p>}</div>}</div>
}
