"use client";

import { useCallback, useEffect, useRef, useState } from "react";

import { apiJson, LOCAL_API_BASE_URL as API, postJson } from "./api-client";
import { versionControls, workflowControls } from "./finalization-presentation.mjs";

type Blocker={code:string;message:string;remediation?:string;category?:string};
type ArtifactState={status:string;verified:boolean;generationEligibility:string;finding?:{code:string;message:string}};
type FinalVersion={finalVersionId:string;finalizationEventId:string;finalizedAt:string;relationship:"CURRENT"|"HISTORICAL";artifacts:ArtifactState};
type Projection={state:string;readiness:null|{ready:boolean;profile:string;blockers:Blocker[]};transcriptCompletion:{state:"NOT_RECORDED"|"CURRENT"|"STALE"};currentFinalVersionId:string|null;latestFinalVersionId:string|null;versions:FinalVersion[]};

const REMEDIATION_LABELS:Record<string,string>={WORKSPACE:"Open Workspace",OPENING:"Review Opening",CERTIFICATION_PAGES:"Review Certification Pages",PRINT_PREVIEW:"Review Preview"};

export default function FinalizationPanel({depositionId,onNavigate}:{depositionId:string;onNavigate:(destination:string)=>void}){
  const [projection,setProjection]=useState<Projection|null>(null),[loading,setLoading]=useState(true),[operation,setOperation]=useState<"completion"|"finalize"|"artifacts"|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[confirming,setConfirming]=useState(false),[renewalReason,setRenewalReason]=useState("");
  const createButton=useRef<HTMLButtonElement>(null),cancelButton=useRef<HTMLButtonElement>(null),operationActive=useRef(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{setProjection(await apiJson<Projection>(`/api/finalization/reporter-projection?depositionId=${encodeURIComponent(depositionId)}`))}catch(reason){setProjection(null);setError(reason instanceof Error?reason.message:"Finalization state could not be loaded.")}finally{setLoading(false)}},[depositionId]);
  useEffect(()=>{let current=true;apiJson<Projection>(`/api/finalization/reporter-projection?depositionId=${encodeURIComponent(depositionId)}`).then(value=>{if(current)setProjection(value)}).catch(reason=>{if(current){setProjection(null);setError(reason instanceof Error?reason.message:"Finalization state could not be loaded.")}}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[depositionId]);
  useEffect(()=>{if(!confirming)return;cancelButton.current?.focus();const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"){setConfirming(false);requestAnimationFrame(()=>createButton.current?.focus())}};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape)},[confirming]);
  const run=useCallback(async(kind:"completion"|"finalize"|"artifacts",work:()=>Promise<unknown>,success:string)=>{if(operationActive.current)return;operationActive.current=true;setOperation(kind);setError("");setNotice("");try{await work();setNotice(success)}catch(reason){setError(reason instanceof Error?reason.message:"The operation was refused.")}finally{setOperation(null);operationActive.current=false;await load()}},[load]);
  const completion=()=>run("completion",()=>postJson("/api/finalization/transcript-completion",{depositionId,completion:projection?.transcriptCompletion.state==="STALE"?{reason:renewalReason.trim()}:{}}),"Transcript production completion was recorded.");
  const finalize=async()=>{setConfirming(false);await run("finalize",()=>postJson("/api/finalization/finalize",{depositionId}),"The canonical final version was created.")};
  const generate=(finalVersionId:string)=>run("artifacts",()=>postJson("/api/finalization/artifacts/generate",{depositionId,finalVersionId}),`${finalVersionId} files were generated and verified.`);
  const cancelConfirmation=()=>{setConfirming(false);requestAnimationFrame(()=>createButton.current?.focus())};
  const controls=workflowControls(projection);
  return <section className="finalization-panel" aria-labelledby="finalization-title" aria-busy={loading||Boolean(operation)}>
    <header><div><span className="eyebrow">FINAL TRANSCRIPT</span><h2 id="finalization-title">Preview &amp; Finalize</h2></div><button type="button" className="secondary-button" onClick={()=>void load()} disabled={loading||Boolean(operation)}>{loading?"Loading…":"Refresh status"}</button></header>
    {error?<p className="finalization-message error" role="alert">{error}</p>:null}{notice?<p className="finalization-message success" role="status">{notice}</p>:null}
    {loading&&!projection?<p className="finalization-message" role="status">Loading authoritative finalization state…</p>:null}
    {projection?.state==="UNKNOWN_DEPOSITION"?<p className="finalization-message error" role="alert">This deposition was not found.</p>:null}
    {projection?.readiness?<div className={`finalization-readiness ${projection.readiness.ready?"ready":"blocked"}`}><strong>{projection.readiness.ready?"Ready for the next finalization step":"Not ready to finalize"}</strong><span>{projection.readiness.ready?"All server-owned readiness checks currently pass.":`${projection.readiness.blockers.length} ${projection.readiness.blockers.length===1?"item requires":"items require"} attention.`}</span></div>:null}
    {projection?.readiness&&!projection.readiness.ready?<ul className="finalization-blockers">{projection.readiness.blockers.map((blocker,index)=><li key={`${blocker.code}-${index}`}><strong>{blocker.code.replaceAll("_"," ")}</strong><p>{blocker.message}</p>{blocker.remediation&&REMEDIATION_LABELS[blocker.remediation]?<button type="button" onClick={()=>onNavigate(blocker.remediation!)}>{REMEDIATION_LABELS[blocker.remediation]}</button>:null}</li>)}</ul>:null}
    {projection&&controls.showCompletion?<div className="finalization-step"><div><strong>{projection.transcriptCompletion.state==="STALE"?"Transcript completion is stale":"Transcript production is not marked complete"}</strong><p>{projection.transcriptCompletion.state==="STALE"?"The transcript or review state changed. Record completion again only after reviewing the current work.":"Record that transcript production has been completed against the current server state."}</p>{projection.transcriptCompletion.state==="STALE"?<label className="finalization-reason">Reason for renewing completion<input value={renewalReason} onChange={event=>setRenewalReason(event.target.value)} placeholder="Describe the correction or review completed" /></label>:null}</div><button type="button" className="primary-button" onClick={()=>void completion()} disabled={Boolean(operation)||(projection.transcriptCompletion.state==="STALE"&&!renewalReason.trim())}>{operation==="completion"?"Recording…":"Mark Transcript Production Complete"}</button></div>:null}
    {controls.showCreateFinal?<div className="finalization-step consequential"><div><strong>Ready to create a canonical final version</strong><p>The server will assign the next FINAL-vN identity and bind it to the current authoritative state.</p></div><button ref={createButton} type="button" className="primary-button" onClick={()=>setConfirming(true)} disabled={Boolean(operation)}>Create Final Version</button></div>:null}
    {projection?.versions.length?<div className="finalization-history"><h3>Final version history</h3>{[...projection.versions].reverse().map(version=>{const versionState=versionControls(version);return <article key={version.finalVersionId} className={versionState.integrityFailure?"integrity-failure":""}><header><div><strong>{version.finalVersionId}{version.artifacts.verified?" — Verified":""}</strong><span>{version.relationship==="CURRENT"?"Current":"Historical"} · {new Date(version.finalizedAt).toLocaleString()}</span></div><span>{version.artifacts.status.replaceAll("_"," ").toLowerCase()}</span></header>
      {versionState.showGenerate?<button type="button" className="primary-button" onClick={()=>void generate(version.finalVersionId)} disabled={Boolean(operation)}>{operation==="artifacts"?"Generating and verifying…":"Generate & Verify Final Files"}</button>:null}
      {versionState.historicalGenerationProhibited?<p className="finalization-message warning">Historical final files are unavailable. Regeneration is not permitted because the deposition changed after this version was finalized.</p>:null}
      {versionState.integrityFailure?<p className="finalization-message error" role="alert"><strong>Integrity verification failed.</strong> {version.artifacts.finding?.message}</p>:null}
      {versionState.showDownloads?<div className="finalization-downloads"><a href={`${API}/api/finalization/artifacts/download?depositionId=${encodeURIComponent(depositionId)}&finalVersionId=${encodeURIComponent(version.finalVersionId)}&kind=docx`}>Final DOCX</a><a href={`${API}/api/finalization/artifacts/download?depositionId=${encodeURIComponent(depositionId)}&finalVersionId=${encodeURIComponent(version.finalVersionId)}&kind=pdf`}>Final PDF</a></div>:null}
    </article>})}</div>:null}
    {confirming?<div className="finalization-confirm-backdrop" role="presentation"><div className="finalization-confirm" role="dialog" aria-modal="true" aria-labelledby="finalization-confirm-title"><h3 id="finalization-confirm-title">Create Final Version?</h3><p>This creates an authoritative finalization version bound to the deposition’s current verified state. The server will assign its FINAL-vN identity.</p><div><button ref={cancelButton} type="button" onClick={cancelConfirmation}>Cancel</button><button type="button" className="primary-button" onClick={()=>void finalize()} disabled={Boolean(operation)}>Confirm Create Final Version</button></div></div></div>:null}
  </section>
}
