"use client";
import {useEffect,useState} from "react";
const API="http://127.0.0.1:4317";
type Device={id:string;name:string;kind:"input"|"loopback"};
type Session={sessionId:string;state:string;sources:Array<{id:string;deviceName:string;state:string;artifact?:{bytes:number|null;sha256:string|null;finalized:boolean}}>};
export default function LiveCaptureScreen({deposition,onBack}:{deposition:{id:string;caseStyle:string;witness:string};onBack:()=>void}){
 const [devices,setDevices]=useState<Device[]>([]),[mic,setMic]=useState(""),[meeting,setMeeting]=useState(""),[session,setSession]=useState<Session|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let current=true;fetch(`${API}/api/live-capture/devices`).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Could not enumerate Windows audio devices.");return payload.devices??[]}).then((available:Device[])=>{if(current){setDevices(available);setMic(available.find(item=>item.kind==="input")?.id||"");setMeeting(available.find(item=>item.kind==="loopback")?.id||"")}}).catch(reason=>{if(current)setError(reason instanceof Error?reason.message:"Could not enumerate audio devices.")});return()=>{current=false}},[]);
 async function post(route:string,payload:object){const response=await fetch(`${API}${route}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error||"Live capture request failed.");return result}
 async function start(){setBusy(true);setError("");try{const configured=await post("/api/live-capture/session",{depositionId:deposition.id,sources:[{id:"local-microphone",role:"LOCAL_MICROPHONE",deviceId:mic,deviceName:devices.find(item=>item.id===mic)?.name},{id:"meeting-audio",role:"VIRTUAL_MEETING_AUDIO",deviceId:meeting,deviceName:devices.find(item=>item.id===meeting)?.name}]});setSession(await post("/api/live-capture/start",{depositionId:deposition.id,sessionId:configured.sessionId}))}catch(reason){setError(reason instanceof Error?reason.message:"Could not start local recording.")}finally{setBusy(false)}}
 async function stop(){if(!session)return;setBusy(true);setError("");try{setSession(await post("/api/live-capture/stop",{depositionId:deposition.id,sessionId:session.sessionId}))}catch(reason){setError(reason instanceof Error?reason.message:"Could not finalize local recording.")}finally{setBusy(false)}}
 const recording=session?.state==="RECORDING";
 return <main className="live-capture-screen"><header><div><span className="eyebrow">WINDOWS LOCAL CAPTURE · PHASE 2</span><h1>Live deposition</h1><p>{deposition.caseStyle} · {deposition.witness}</p></div><button className="secondary-button" type="button" onClick={onBack} disabled={recording}>Back to Workspace</button></header><section className="live-capture-card"><h2>Independent audio sources</h2><p>Each source is recorded to its own lossless WAV file. Deepgram and the network are not used by this recorder.</p>{error&&<p className="analysis-error" role="alert">{error}</p>}<div className="live-source-grid"><label><strong>CH1 · Local microphone</strong><select value={mic} onChange={event=>setMic(event.target.value)} disabled={Boolean(session)}><option value="">Select a microphone</option>{devices.map(device=><option value={device.id} key={`mic-${device.id}`}>{device.name}</option>)}</select></label><label><strong>CH2 · Virtual meeting audio</strong><select value={meeting} onChange={event=>setMeeting(event.target.value)} disabled={Boolean(session)}><option value="">Select a loopback/virtual input</option>{devices.map(device=><option value={device.id} key={`meeting-${device.id}`}>{device.name}</option>)}</select></label></div>{!session?<button className="primary-button" type="button" disabled={busy||!mic||!meeting||mic===meeting} onClick={()=>void start()}>{busy?"Starting local recorders…":"Start independent local recording"}</button>:recording?<button className="danger-button" type="button" disabled={busy} onClick={()=>void stop()}>{busy?"Finalizing channels…":"Stop and finalize recordings"}</button>:<div className="live-finalized"><strong>Local recording {session.state.toLowerCase()}</strong>{session.sources.map(source=><p key={source.id}>{source.deviceName}: {source.artifact?.finalized?`${source.artifact.bytes?.toLocaleString()} bytes · SHA-256 ${source.artifact.sha256?.slice(0,12)}…`:source.state}</p>)}</div>}</section></main>
}
