"use client";
import { useEffect, useMemo, useState } from "react";
const API="http://127.0.0.1:4317";
export type TranscriptDeposition={id:string;caseStyle:string;witness:string;depositionDate:string;courtReporterName:string;audioFiles:string[];audioIntakeIds?:string[];keyterms?:string[]};
type Audit={uploadId:string;originalName:string;selectedSource:string;automaticSelection?:{winner:string;reason:string};transcripts?:Record<string,DeepgramTranscript>};
type Paragraph={speaker?:number;start?:number;end?:number;sentences?:Array<{text:string;start?:number;end?:number}>};
type DeepgramTranscript={transcript:string;confidence:number|null;paragraphs?:Paragraph[];utterances?:Array<{speaker?:number;start?:number;end?:number;transcript?:string}>;keytermCount:number;options?:Record<string,string>;createdAt:string;diarization?:{requested:boolean;available:boolean};audioDelivery?:{requestedSource:string;deliveredSource:string;converted:boolean;reason:string}};
function time(seconds=0){const total=Math.max(0,Math.floor(seconds));return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
export default function TranscriptCreationScreen({deposition,onBack}:{deposition:TranscriptDeposition;onBack:()=>void}){
 const [audits,setAudits]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[running,setRunning]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{const values=await Promise.all((deposition.audioIntakeIds||[]).map(async uploadId=>{const response=await fetch(`${API}/api/audio/audit?uploadId=${encodeURIComponent(uploadId)}`);const body=await response.json();if(!response.ok)throw new Error(body.error);return body}));if(live)setAudits(values)}catch(e){if(live)setError(e instanceof Error?e.message:"Could not load the audio records.")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[deposition.audioIntakeIds]);
 const selected=useMemo(()=>audits.map(audit=>({audit,transcript:audit.transcripts?.[audit.selectedSource]})),[audits]);
 async function createTranscript(audit:Audit){setRunning(audit.uploadId);setError("");try{const response=await fetch(`${API}/api/audio/transcribe`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({uploadId:audit.uploadId,source:audit.selectedSource,keyterms:deposition.keyterms||[]})});const body=await response.json();if(!response.ok)throw new Error(body.error);const refreshed=await fetch(`${API}/api/audio/audit?uploadId=${encodeURIComponent(audit.uploadId)}`).then(r=>r.json());setAudits(current=>current.map(item=>item.uploadId===audit.uploadId?refreshed:item))}catch(e){setError(e instanceof Error?e.message:"Deepgram transcription failed.")}finally{setRunning("")}}
 function speaker(value:number|undefined){return Number.isInteger(value)?`Speaker ${value!+1}`:"Speaker unavailable"} function renderTranscript(value:DeepgramTranscript){const paragraphs=value.paragraphs||[];if(paragraphs.length)return paragraphs.map((paragraph,index)=><article className="dg-paragraph" key={`${paragraph.start}-${index}`}><header><span>{speaker(paragraph.speaker)}</span><time>{time(paragraph.start)}</time></header><p>{(paragraph.sentences||[]).map(sentence=>sentence.text).join(" ")}</p></article>);const utterances=value.utterances||[];if(utterances.length)return utterances.map((utterance,index)=><article className="dg-paragraph" key={`${utterance.start}-${index}`}><header><span>{speaker(utterance.speaker)}</span><time>{time(utterance.start)}</time></header><p>{utterance.transcript}</p></article>);return <p className="plain-transcript">{value.transcript}</p>}
 return <main className="transcript-shell"><header className="transcript-topbar"><button className="back-button" onClick={onBack}>← Back to depositions</button><span>DEPO<span>PRO</span></span><small>Deepgram Nova‑3</small></header><section className="transcript-hero"><span className="eyebrow">TRANSCRIPT CREATION</span><h1>{deposition.caseStyle}</h1><p>Witness: {deposition.witness}</p><div className="transcript-settings"><span>Nova‑3</span><span>English</span><span>Speaker diarization</span><span>Filler words</span><span>Numerals</span><span>Paragraphs</span><span>Smart format</span><span>{deposition.keyterms?.length||0} keyterms</span></div></section>
 <section className="transcript-workspace"><div className="transcript-workspace-heading"><div><h2>Create the transcript</h2><p>Depo‑Pro uses the automatically selected audio source and the case keyterm file. Compatible M4A files are sent directly; a WAV fallback is created automatically only if Deepgram cannot decode the source.</p></div></div>{error&&<p className="analysis-error" role="alert">{error}</p>}{loading?<div className="transcript-empty">Loading audio records…</div>:!audits.length?<div className="transcript-empty"><h3>No linked audio records</h3><p>This deposition was created before local audio intake tracking was added. Create a new deposition or upload its audio again.</p></div>:selected.map(({audit,transcript},index)=><section className="transcript-file" key={audit.uploadId}><header><div><span className="audio-sequence">{index+1}</span><div><h3>{deposition.audioFiles[index]||audit.originalName}</h3><p>Using {audit.selectedSource} audio{audit.automaticSelection?` · automatically selected ${audit.automaticSelection.winner}`:""}</p></div></div><button className="primary-button" onClick={()=>createTranscript(audit)} disabled={running===audit.uploadId}>{running===audit.uploadId?"Creating transcript…":transcript?"Create again":"Create transcript"}</button></header>{transcript?<div className="deepgram-result"><div className="deepgram-result-meta"><span>Confidence {transcript.confidence===null?"—":`${(transcript.confidence*100).toFixed(1)}%`}</span><span>{transcript.keytermCount} keyterms</span><span>{transcript.audioDelivery?.converted?"Automatic WAV fallback used":"Original format accepted"}</span><span>{transcript.diarization?.available?"Speakers identified":"Speaker identification unavailable"}</span><span>{new Date(transcript.createdAt).toLocaleString()}</span></div>{transcript.audioDelivery?.converted&&<p className="analysis-note">{transcript.audioDelivery.reason}</p>}{transcript.diarization&&!transcript.diarization.available&&<p className="analysis-warning">Deepgram did not return speaker metadata. Depo-Pro has not assigned a default speaker.</p>}{renderTranscript(transcript)}</div>:<div className="transcript-ready"><strong>Ready for Deepgram</strong><p>The source and formatting options have been prepared automatically.</p></div>}</section>)}</section></main>
}
