"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { groupTranscriptSegments } from "./transcript-paragraphs.mjs";
const API="http://127.0.0.1:4317";
export type TranscriptDeposition={id:string;caseStyle:string;witness:string;depositionDate:string;courtReporterName:string;audioFiles:string[];audioIntakeIds?:string[];keyterms?:string[]};
type Audit={uploadId:string;originalName:string;selectedSource:string;automaticSelection?:{winner:string;reason:string}};
type Job={jobId:string;uploadId:string;status:"processing"|"completed"|"failed";startedAt:string;completedAt?:string;keyterms?:{count:number};failure?:{message:string};response?:{deliveredAudio?:{converted?:boolean}}};
type Segment={id:string;sourceJobIdentity:string;sourceUploadId:string;asrWordIds:string[];deepgramSpeaker:number|null;speakerIdentity:string|null;transcriptRole:string|null;start:number|null;end:number|null;text:string};
type TranscriptParagraph=Segment&{segmentIds:string[]};
type Working={speakerMap:{status:string;assignments:Array<Assignment>};segments:Segment[];updatedAt:string};
type Candidate={id:string;label:string;defaultRole:string};type Assignment={sourceJobIdentity:string;deepgramSpeaker:number;speakerIdentity:string;transcriptRole:string};
function time(seconds=0){const total=Math.max(0,Math.floor(seconds));return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
async function getJson(url:string){const response=await fetch(url),body=await response.json();if(!response.ok)throw new Error(body.error||"Request failed.");return body}
export default function TranscriptCreationScreen({deposition,onBack,onInsertionPages}:{deposition:TranscriptDeposition;onBack:()=>void;onInsertionPages?:()=>void}){
 const [audits,setAudits]=useState<Audit[]>([]),[jobs,setJobs]=useState<Job[]>([]),[working,setWorking]=useState<Working|null>(null),[candidates,setCandidates]=useState<Candidate[]>([]),[roles,setRoles]=useState<string[]>([]),[assignments,setAssignments]=useState<Record<string,Assignment>>({}),[loading,setLoading]=useState(true),[running,setRunning]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[overrideReason,setOverrideReason]=useState("");
 const refresh=useCallback(async()=>{const [auditValues,jobResult,candidateResult]=await Promise.all([Promise.all((deposition.audioIntakeIds||[]).map(uploadId=>getJson(`${API}/api/audio/audit?uploadId=${encodeURIComponent(uploadId)}`))),getJson(`${API}/api/transcription/jobs?depositionId=${encodeURIComponent(deposition.id)}`),getJson(`${API}/api/transcript/speaker-candidates?depositionId=${encodeURIComponent(deposition.id)}`)]);setAudits(auditValues);setJobs(jobResult.jobs||[]);setCandidates(candidateResult.candidates||[]);setRoles(candidateResult.roles||[]);try{const transcript=await getJson(`${API}/api/transcript/working?depositionId=${encodeURIComponent(deposition.id)}`);setWorking(transcript);const existing:Record<string,Assignment>={};for(const item of transcript.speakerMap?.assignments||[])existing[`${item.sourceJobIdentity}:${item.deepgramSpeaker}`]=item;setAssignments(existing)}catch{setWorking(null)}},[deposition.audioIntakeIds,deposition.id]);
 useEffect(()=>{let live=true;(async()=>{try{await refresh()}catch(e){if(live)setError(e instanceof Error?e.message:"Could not load transcription state.")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[refresh]);
 const jobByUpload=useMemo(()=>new Map(jobs.map(job=>[job.uploadId,job])),[jobs]),speakerKeys=useMemo(()=>{const found=new Map<string,{sourceJobIdentity:string;deepgramSpeaker:number}>();for(const segment of working?.segments||[])if(Number.isInteger(segment.deepgramSpeaker)){const value={sourceJobIdentity:segment.sourceJobIdentity,deepgramSpeaker:segment.deepgramSpeaker!};found.set(`${value.sourceJobIdentity}:${value.deepgramSpeaker}`,value)}return [...found.values()]},[working]);
 async function createTranscript(audit:Audit){setRunning(audit.uploadId);setError("");setNotice("");try{const response=await fetch(`${API}/api/audio/transcribe`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({depositionId:deposition.id,uploadId:audit.uploadId,keytermOverrideReason:overrideReason})}),body=await response.json();if(!response.ok)throw new Error(body.error);setWorking(body.workingTranscript);setNotice(body.cached?"Loaded the preserved, integrity-verified transcription. No Deepgram request was made.":"Deepgram evidence was preserved and the Working Transcript was updated.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Deepgram transcription failed.")}finally{setRunning("")}}
 function updateAssignment(sourceJobIdentity:string,deepgramSpeaker:number,field:"speakerIdentity"|"transcriptRole",value:string){const key=`${sourceJobIdentity}:${deepgramSpeaker}`;setAssignments(existing=>{const current=existing[key]||{sourceJobIdentity,deepgramSpeaker,speakerIdentity:"",transcriptRole:""};return{...existing,[key]:{...current,[field]:value}}})}
 async function saveSpeakers(){setError("");try{const selected=speakerKeys.map(item=>assignments[`${item.sourceJobIdentity}:${item.deepgramSpeaker}`]).filter(item=>item?.speakerIdentity&&item?.transcriptRole),response=await fetch(`${API}/api/transcript/speaker-map`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({depositionId:deposition.id,assignments:selected})}),body=await response.json();if(!response.ok)throw new Error(body.error);setWorking(body);setNotice(body.speakerMap.status==="reconciled"?"Every observed speaker has been reconciled.":"Speaker assignments were saved; unresolved speakers remain.")}catch(e){setError(e instanceof Error?e.message:"Speaker reconciliation failed.")}}
 return <main className="transcript-shell"><header className="transcript-topbar"><button className="back-button" onClick={onBack}>← Back to depositions</button>{onInsertionPages&&<button type="button" className="secondary-button" onClick={onInsertionPages}>Certification pages</button>}<span>DEPO<span>PRO</span></span><small>Deepgram Nova‑3 · Diarizer v2</small></header><section className="transcript-hero"><span className="eyebrow">TRANSCRIPT CREATION</span><h1>{deposition.caseStyle}</h1><p>Witness: {deposition.witness}</p><div className="transcript-settings"><span>Server-authoritative keyterms</span><span>Immutable raw response</span><span>Word-level evidence</span><span>{deposition.keyterms?.length||0} keyterms</span></div></section>
 <section className="transcript-workspace"><div className="transcript-workspace-heading"><div><h2>Create or resume the transcript</h2><p>Completed jobs are loaded from the deposition workspace and are never submitted to Deepgram twice.</p></div></div>{error&&<p className="analysis-error" role="alert">{error}</p>}{notice&&<p className="analysis-note" role="status">{notice}</p>}{(deposition.keyterms?.length||0)>50&&<label className="transcript-field">Required keyterm override reason<input value={overrideReason} onChange={event=>setOverrideReason(event.target.value)} placeholder="Record why more than 50 terms are necessary"/></label>}{loading?<div className="transcript-empty">Loading preserved transcription state…</div>:!audits.length?<div className="transcript-empty"><h3>No linked audio records</h3><p>Add audio to this deposition before creating its transcript.</p></div>:audits.map((audit,index)=>{const job=jobByUpload.get(audit.uploadId),segments=(working?.segments||[]).filter(item=>item.sourceUploadId===audit.uploadId),paragraphs=groupTranscriptSegments(segments) as TranscriptParagraph[];return <section className="transcript-file" key={audit.uploadId}><header><div><span className="audio-sequence">{index+1}</span><div><h3>{deposition.audioFiles[index]||audit.originalName}</h3><p>{job?`Job ${job.status} · ${job.jobId.slice(0,12)}…`:`Frozen ${audit.selectedSource} source ready`}</p></div></div><button className="primary-button" onClick={()=>createTranscript(audit)} disabled={running===audit.uploadId||job?.status==="processing"}>{running===audit.uploadId?"Creating transcript…":job?.status==="completed"?"Verify preserved result":job?.status==="failed"?"Retry failed job":"Create transcript"}</button></header>{job?.failure&&<p className="analysis-error">{job.failure.message}</p>}{segments.length?<div className="deepgram-result"><div className="deepgram-result-meta"><span>{segments.length} utterances · {paragraphs.length} paragraphs</span><span>{job?.keyterms?.count||0} keyterms</span><span>{job?.response?.deliveredAudio?.converted?"Lossless WAV fallback":"Frozen deposition audio"}</span><span>{working?.speakerMap.status.replaceAll("_"," ")}</span></div>{paragraphs.map(paragraph=><article className="dg-paragraph" key={paragraph.segmentIds.join(":")}><header><span>{paragraph.speakerIdentity||`Deepgram speaker ${(paragraph.deepgramSpeaker??0)+1}`}{paragraph.transcriptRole?` · ${paragraph.transcriptRole.replaceAll("_"," ")}`:""}</span><time>{time(paragraph.start??0)}</time></header><p>{paragraph.text}</p></article>)}</div>:<div className="transcript-ready"><strong>{job?.status==="failed"?"Job failed":"Ready for Deepgram"}</strong><p>{job?.status==="failed"?"The failed attempt and any vendor error response remain preserved.":"The exact frozen source and request configuration will be verified before submission."}</p></div>}</section>})}
 {speakerKeys.length>0&&<section className="transcript-file"><header><div><div><h3>Reconcile speakers</h3><p>Assignments are scoped to each recording and validated against the Canonical Deposition Data Record.</p></div></div><button className="primary-button" onClick={saveSpeakers}>Save speaker map</button></header><div className="speaker-map-grid">{speakerKeys.map(item=>{const key=`${item.sourceJobIdentity}:${item.deepgramSpeaker}`,assignment=assignments[key];return <div className="form-row" key={key}><label>Job {item.sourceJobIdentity.slice(0,8)} · Speaker {item.deepgramSpeaker+1}<select value={assignment?.speakerIdentity||""} onChange={event=>{const candidate=candidates.find(value=>value.id===event.target.value);updateAssignment(item.sourceJobIdentity,item.deepgramSpeaker,"speakerIdentity",event.target.value);if(candidate&&(!assignment?.transcriptRole))updateAssignment(item.sourceJobIdentity,item.deepgramSpeaker,"transcriptRole",roles.includes(candidate.defaultRole)?candidate.defaultRole:"OTHER")}}><option value="">Unresolved</option>{candidates.map(candidate=><option value={candidate.id} key={candidate.id}>{candidate.label}</option>)}</select></label><label>Transcript role<select value={assignment?.transcriptRole||""} onChange={event=>updateAssignment(item.sourceJobIdentity,item.deepgramSpeaker,"transcriptRole",event.target.value)}><option value="">Select role</option>{roles.map(role=><option key={role}>{role}</option>)}</select></label></div>})}</div></section>}
 </section></main>
}
