import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { readAudioAudit, resolveAudioItem } from "./audio-pipeline.mjs";
import { depositionStorageRoot, resolveDefaultDepositionsRoot } from "./storage-config.mjs";
import { createCanonicalDepositionRecord } from "./canonical-deposition-record.mjs";

const ID_PATTERN=/^DEP-\d{8}-[A-Z0-9]{5}$/;
function base(_root,{storageRoot}={}){return storageRoot?path.resolve(storageRoot):depositionStorageRoot()}
function within(candidate,parent){const relative=path.relative(path.resolve(parent),path.resolve(candidate));return relative&&!relative.startsWith("..")&&!path.isAbsolute(relative)}
function safeName(value,fallback){return path.basename(String(value||fallback)).replace(/[^a-zA-Z0-9._ -]/g,"_")}
function pathPart(value,label){const normalized=String(value||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/[^a-z0-9-]+/g,"_").replace(/_+/g,"_").replace(/^[-_]+|[-_]+$/g,"");if(!normalized)throw new Error(`${label} is required to create the deposition folder.`);return normalized}
function personName(value,label){const name=String(value||"").trim();if(!name)throw new Error(`${label} is required to create the deposition folder.`);const suffixes=new Set(["jr","jr.","sr","sr.","ii","iii","iv"]);let first,last;if(name.includes(",")&&!suffixes.has(name.split(",").at(-1).trim().toLowerCase())){const parts=name.split(",");last=parts[0];first=parts.slice(1).join(" ").trim()}else{const parts=name.replace(/,/g,"").split(/\s+/).filter(Boolean);while(parts.length>1&&suffixes.has(parts.at(-1).toLowerCase()))parts.pop();first=parts[0];last=parts.at(-1)}return{first:pathPart(first,`${label} first name`),last:pathPart(last,`${label} last name`)}}
function reporterFolder(value){const {first,last}=personName(value,"Court reporter");return `${last}_${first[0]}`}
function causeFolder(metadata){return pathPart(metadata?.causeNumber||metadata?.ufmData?.cause_number||metadata?.ufmData?.causeNumber,"Cause number")}
function depositionFolder(metadata){const {first,last}=personName(metadata?.witness,"Deponent"),date=pathPart(requiredText(metadata?.depositionDate,"Deposition date"),"Deposition date");return `${last}_${first}_${date}`}
function atomicJson(file,value){const temporary=`${file}.${crypto.randomUUID()}.tmp`,descriptor=fs.openSync(temporary,"wx");try{fs.writeFileSync(descriptor,JSON.stringify(value,null,2));fs.fsyncSync(descriptor)}finally{fs.closeSync(descriptor)}fs.renameSync(temporary,file)}
function commitDirectory(source,target,{rename=fs.renameSync,wait=milliseconds=>Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,milliseconds),attempts=8,delayBaseMs=350}={}){for(let attempt=1;attempt<=attempts;attempt++){try{rename(source,target);return}catch(error){if(!["EPERM","EBUSY","EACCES"].includes(error?.code))throw error;if(attempt===attempts){const blocked=new Error(`Windows blocked the completed deposition folder rename after ${attempts} attempts. Close programs using the deposition files or check folder permissions, then try again.`,{cause:error});blocked.code="DEPOSITION_COMMIT_BLOCKED";throw blocked}wait(delayBaseMs*attempt)}}}
function requiredText(value,label){const text=String(value||"").trim();if(!text)throw new Error(`${label} is required.`);return text}
function depositionDirectories(root,options={}){const directory=base(root,options);fs.mkdirSync(directory,{recursive:true});const found=[];for(const reporter of fs.readdirSync(directory,{withFileTypes:true})){if(!reporter.isDirectory()||reporter.name.startsWith("."))continue;const reporterPath=path.join(directory,reporter.name);for(const cause of fs.readdirSync(reporterPath,{withFileTypes:true})){if(!cause.isDirectory()||cause.name.startsWith("."))continue;const causePath=path.join(reporterPath,cause.name);for(const deposition of fs.readdirSync(causePath,{withFileTypes:true})){if(deposition.isDirectory()&&!deposition.name.startsWith("."))found.push(path.join(causePath,deposition.name))}}}return found}
export function depositionDirectory(root,id,options={}){if(!ID_PATTERN.test(String(id)))throw new Error("Invalid deposition ID.");for(const directory of depositionDirectories(root,options)){const record=path.join(directory,"deposition.json");if(!fs.existsSync(record))continue;try{if(JSON.parse(fs.readFileSync(record,"utf8")).id===id)return directory}catch{continue}}throw new Error("Deposition was not found.")}

export function scanDepositions(root,options={}){const storageRoot=base(root,options),depositions=[],issues=[];for(const folder of depositionDirectories(root,options)){
  const relative=path.relative(storageRoot,folder),record=path.join(folder,"deposition.json");
  if(!fs.existsSync(record)){issues.push({folder:relative,code:"ORPHANED_FOLDER",message:"deposition.json is missing."});continue}
  try{const value=JSON.parse(fs.readFileSync(record,"utf8"));if(!ID_PATTERN.test(value.id)||!value.caseStyle||!value.witness)throw new Error("Required identity fields are missing or inconsistent.");depositions.push(value)}catch(error){issues.push({folder:relative,code:"MALFORMED_DEPOSITION",message:error instanceof Error?error.message:"Invalid deposition metadata."})}
 }depositions.sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)));return{depositions,issues}}

function writeArtifact(directory,relative,artifact){if(!artifact?.base64)return null;const target=path.join(directory,...relative.split("/"));if(!within(target,directory))throw new Error("Intake artifact path escaped the deposition folder.");fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,Buffer.from(artifact.base64,"base64"),{flag:"wx"});return relative}

export function createDeposition(root,input,options={}){const metadata=input?.deposition||{},id=String(metadata.id||"");if(!ID_PATTERN.test(id))throw new Error("Invalid deposition ID.");const rootDirectory=base(root,options),reporter=reporterFolder(metadata.courtReporterName),cause=causeFolder(metadata),deposition=depositionFolder(metadata),causeDirectory=path.join(rootDirectory,reporter,cause),finalDirectory=path.join(causeDirectory,deposition);if(!within(finalDirectory,rootDirectory))throw new Error("Deposition path escaped its storage root.");fs.mkdirSync(causeDirectory,{recursive:true});if(fs.existsSync(finalDirectory))throw new Error(`A deposition already exists for ${metadata.witness} on ${metadata.depositionDate} in cause number ${metadata.causeNumber}.`);const staging=path.join(causeDirectory,`.creating-${deposition}-${crypto.randomUUID()}`);fs.mkdirSync(staging,{recursive:false});
 try{
  for(const name of ["intake","audio/original","audio/processed","deepgram","transcript","exhibits","ufm","certification/history"])fs.mkdirSync(path.join(staging,...name.split("/")),{recursive:true});
  const artifacts=input.artifacts||{},noticeName=artifacts.notice?safeName(artifacts.notice.name,"notice.bin"):"",courtOrderName=artifacts.courtOrder?safeName(artifacts.courtOrder.name,"court-order.bin"):"";
  if(artifacts.notice)writeArtifact(staging,`intake/${noticeName}`,artifacts.notice);if(artifacts.courtOrder)writeArtifact(staging,`intake/${courtOrderName}`,artifacts.courtOrder);
  const supporting=(artifacts.supportingFiles||[]).map((artifact,index)=>writeArtifact(staging,`intake/supporting/${String(index+1).padStart(2,"0")}-${safeName(artifact.name,"document.bin")}`,artifact));
  const audio=[];for(const uploadId of metadata.audioIntakeIds||[]){const audit=readAudioAudit(root,uploadId),item=resolveAudioItem(audit),source=path.resolve(root,"data",item.key);const category=audit.selectedSource==="processed"?"processed":"original",name=safeName(audit.selectedSource==="processed"?path.basename(item.key):audit.originalName,path.basename(item.key)),relative=`audio/${category}/${name}`,target=path.join(staging,...relative.split("/"));fs.copyFileSync(source,target,fs.constants.COPYFILE_EXCL);/* copyFileSync returns only after its internal handles are closed. */audio.push({uploadId,source:audit.selectedSource,operationId:audit.selectedDerivativeOperationId||null,sha256:item.sha256,path:relative,name})}
  const canonicalData=createCanonicalDepositionRecord({...metadata,...(metadata.canonicalSeed||{}),caseStyle:metadata.caseStyle,witness:metadata.witness,causeNumber:metadata.causeNumber,depositionDate:metadata.depositionDate,deponentType:metadata.deponentType});
  const now=new Date().toISOString(),record={schemaVersion:"1.1.0",id,caseStyle:requiredText(metadata.caseStyle,"Case style"),witness:requiredText(metadata.witness,"Witness"),deponentType:String(metadata.deponentType||"Fact witness"),depositionDate:requiredText(metadata.depositionDate,"Deposition date"),courtReporterId:String(metadata.courtReporterId||""),courtReporterName:String(metadata.courtReporterName||""),causeNumber:requiredText(metadata.causeNumber,"Cause number"),canonicalData,storagePath:`${reporter}/${cause}/${deposition}`,intakeNotes:String(metadata.intakeNotes||""),noticeName,courtOrderName,audioFiles:audio.map(item=>item.name),audioIntakeIds:audio.map(item=>item.uploadId),audio,keytermCount:Array.isArray(metadata.keyterms)?metadata.keyterms.length:0,keyterms:Array.isArray(metadata.keyterms)?metadata.keyterms:[],paths:{intake:"intake/intake.json",canonicalData:"intake/canonical-deposition-record.json",workingTranscript:"transcript/working.json"},createdAt:now,updatedAt:now};
  atomicJson(path.join(staging,"intake","intake.json"),{schemaVersion:"1.0.0",notice:noticeName||null,courtOrder:courtOrderName||null,supporting,keyterms:record.keyterms,deepgramArtifact:metadata.deepgramArtifact||{},ufmData:metadata.ufmData||{},warnings:metadata.warnings||[],audio});
  atomicJson(path.join(staging,"audio","audit.json"),{schemaVersion:"1.0.0",items:audio});atomicJson(path.join(staging,"intake","canonical-deposition-record.json"),canonicalData);atomicJson(path.join(staging,"deposition.json"),record);commitDirectory(staging,finalDirectory);return record;
 }catch(error){fs.rmSync(staging,{recursive:true,force:true});throw error}}

export function readDepositionIntake(root,id,options={}){const file=path.join(depositionDirectory(root,id,options),"intake","intake.json");if(!fs.existsSync(file))throw new Error("Deposition intake record was not found.");return JSON.parse(fs.readFileSync(file,"utf8"))}
export function resolveDepositionAudio(root,id,index,options={}){const directory=depositionDirectory(root,id,options),record=JSON.parse(fs.readFileSync(path.join(directory,"deposition.json"),"utf8")),item=record.audio?.[Number(index)];if(!item)throw new Error("Deposition audio was not found.");const file=path.resolve(directory,...String(item.path).split("/"));if(!within(file,directory)||!fs.existsSync(file))throw new Error("Deposition audio reference is invalid.");return{file,item}}

export const _testing={within,safeName,pathPart,personName,reporterFolder,causeFolder,depositionFolder,atomicJson,commitDirectory,ID_PATTERN,resolveDefaultDepositionsRoot};
