import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { buildDeepgramRequest, DEEPGRAM_CONFIGURATION_VERSION, DEEPGRAM_PLAYGROUND_OPTIONS } from "./deepgram-service.mjs";
import { depositionDirectory } from "./deposition-store.mjs";
import { withTranscriptContentHash } from "./transcript-content-hash.mjs";
import { KEYTERM_API_LIMIT, KEYTERM_PRODUCT_CAP, KEYTERM_TOKEN_BUDGET, estimateKeytermTokens } from "./keyterm-limits.mjs";
import { appendOperations, undoLast, validateOverlay } from "./reporter-overlay.mjs";

export { KEYTERM_PRODUCT_CAP, KEYTERM_TOKEN_BUDGET } from "./keyterm-limits.mjs";
export const TRANSCRIPT_ROLES=Object.freeze(["QUESTIONING_ATTORNEY","DEFENDING_ATTORNEY","WITNESS","COURT_REPORTER","VIDEOGRAPHER","INTERPRETER","OTHER"]);
const sha=value=>crypto.createHash("sha256").update(value).digest("hex"),jsonBytes=value=>Buffer.from(JSON.stringify(value,null,2)),ACTIVE_JOBS=new Set();
function readJson(file){return JSON.parse(fs.readFileSync(file,"utf8"))}
function atomic(file,bytes){fs.mkdirSync(path.dirname(file),{recursive:true});const temporary=`${file}.${crypto.randomUUID()}.tmp`,descriptor=fs.openSync(temporary,"wx");try{fs.writeFileSync(descriptor,bytes);fs.fsyncSync(descriptor)}finally{fs.closeSync(descriptor)}fs.renameSync(temporary,file)}
function hashFile(file){return sha(fs.readFileSync(file))}
function relative(directory,file){return path.relative(directory,file).replaceAll("\\","/")}
const estimateTokens=estimateKeytermTokens;
function observedSpeakerKeys(working){return new Set((working.segments||[]).filter(item=>Number.isInteger(item.deepgramSpeaker)).map(item=>`${item.sourceJobIdentity}:${item.deepgramSpeaker}`))}
function assignmentKey(item){return `${item.sourceJobIdentity}:${item.deepgramSpeaker}`}
function applySpeakerAssignments(working,assignments=working.speakerMap?.assignments||[]){const map=new Map(assignments.map(item=>[assignmentKey(item),item])),segments=(working.segments||[]).map(segment=>{const match=map.get(`${segment.sourceJobIdentity}:${segment.deepgramSpeaker}`);return match?{...segment,speakerIdentity:match.speakerIdentity,transcriptRole:match.transcriptRole}:{...segment,speakerIdentity:null,transcriptRole:null}}),observed=observedSpeakerKeys({...working,segments}),covered=new Set(assignments.map(assignmentKey)),status=!observed.size?"not_applicable":[...observed].every(key=>covered.has(key))?"reconciled":covered.size?"partially_reconciled":"unreconciled";return{...working,speakerMap:{...(working.speakerMap||{}),status,assignments},segments}}

export function authoritativeKeyterms(intake,{overrideReason=""}={}){const source=Array.isArray(intake?.deepgramArtifact?.wire)?intake.deepgramArtifact.wire:intake?.keyterms;if(!Array.isArray(source))throw new Error("The saved deposition intake does not contain an authoritative Deepgram keyterm array.");const seen=new Set(),wire=[];for(const value of source){const term=String(value).trim();if(!term)continue;const key=term.toLocaleLowerCase("en-US");if(seen.has(key))throw new Error(`The saved keyterm wire array contains a duplicate term: ${term}`);seen.add(key);wire.push(term)}if(wire.length>KEYTERM_API_LIMIT)throw new Error(`The saved keyterm wire array exceeds Deepgram's ${KEYTERM_API_LIMIT}-term API limit.`);if(wire.length>KEYTERM_PRODUCT_CAP&&!String(overrideReason).trim())throw new Error(`More than ${KEYTERM_PRODUCT_CAP} keyterms requires an explicit recorded override reason.`);const estimatedTokens=estimateTokens(wire);if(estimatedTokens>KEYTERM_TOKEN_BUDGET)throw new Error(`The final Deepgram keyterm request is estimated at ${estimatedTokens} tokens and exceeds Depo-Pro's ${KEYTERM_TOKEN_BUDGET}-token submission budget.`);return{wire,estimatedTokens,overrideReason:wire.length>KEYTERM_PRODUCT_CAP?String(overrideReason).trim():null,sha256:sha(jsonBytes(wire))}}
export function transcriptionIdentity({audioSha256,rxOperationId=null,keytermSetSha256,configurationVersion=DEEPGRAM_CONFIGURATION_VERSION,diarizerModel=DEEPGRAM_PLAYGROUND_OPTIONS.diarize_model}){const input={audioSha256,rxOperationId,configurationVersion,diarizerModel,keytermSetSha256};return{input,sha256:sha(jsonBytes(input))}}

function validateRaw(raw){const alternative=raw?.results?.channels?.[0]?.alternatives?.[0];if(!alternative||!Array.isArray(alternative.words))throw new Error("Deepgram response is missing the primary channel word evidence.");return alternative}
function deriveEvidence(raw,context){const alternative=validateRaw(raw);return{schemaVersion:"1.1.0",recordType:"CANONICAL_ASR_EVIDENCE",immutable:true,jobIdentity:context.identity.sha256,rawResponseSha256:context.rawResponseSha256,sourceAudio:context.identity.input,deliveredAudio:context.deliveredAudio,requestId:raw?.metadata?.request_id||null,models:raw?.metadata?.models||[],diarizeInfo:raw?.metadata?.diarize_info??null,createdAt:context.completedAt,words:alternative.words.map((word,index)=>({id:`${context.identity.sha256}:word:${index+1}`,channel:0,word:String(word.word??""),punctuatedWord:String(word.punctuated_word??word.word??""),start:Number.isFinite(word.start)?word.start:null,end:Number.isFinite(word.end)?word.end:null,confidence:Number.isFinite(word.confidence)?word.confidence:null,deepgramSpeaker:Number.isInteger(word.speaker)?word.speaker:null,speakerConfidence:Number.isFinite(word.speaker_confidence)?word.speaker_confidence:null}))}}
// Word-to-utterance assignment is a PARTITION, not a per-utterance overlap query.
//
// It used to be `word.start < item.end && word.end > item.start` evaluated independently for
// each utterance, so a word straddling a boundary matched both and landed in two segments. The
// first live run produced ten such words across 12,185. That falsifies the invariant the
// reporter overlay rests on -- every Deepgram word appears exactly once -- and a split built on
// top of it would bake the defect into the write path.
//
// Resolution is first-match in document order: utterances are walked in order and a word is
// claimed by the first one it overlaps, so a straddling word stays with the utterance that
// began earlier, where its first syllable was spoken. Deterministic, and it changes no
// utterance boundary -- only which segment claims the word.
export function assignWordsToUtterances(utterances=[],words=[]){
  const claimed=new Set();
  return utterances.map(item=>{
    const ids=[];
    for(const word of words){
      if(word.start===null||word.end===null||word.start===undefined||word.end===undefined||claimed.has(word.id))continue;
      if(word.start<(item.end??Infinity)&&word.end>(item.start??-Infinity)){claimed.add(word.id);ids.push(word.id)}
    }
    return ids;
  });
}
function deriveSegments(raw,evidence,context){const utterances=raw?.results?.utterances||[],base=(item,index,ids)=>({id:`${context.identity.sha256}:segment:${index+1}`,sourceJobIdentity:context.identity.sha256,sourceUploadId:context.uploadId,sourceOrdinal:context.sourceOrdinal,asrWordIds:ids,text:String(item.transcript??""),deepgramSpeaker:Number.isInteger(item.speaker)?item.speaker:null,speakerIdentity:null,transcriptRole:null,start:Number.isFinite(item.start)?item.start:null,end:Number.isFinite(item.end)?item.end:null});if(utterances.length){const assigned=assignWordsToUtterances(utterances,evidence.words);return utterances.map((item,index)=>base(item,index,assigned[index]))}const groups=[];for(const word of evidence.words){const current=groups.at(-1);if(!current||current.speaker!==word.deepgramSpeaker)groups.push({speaker:word.deepgramSpeaker,words:[word]});else current.words.push(word)}return groups.map((group,index)=>base({speaker:group.speaker,start:group.words[0].start,end:group.words.at(-1).end,transcript:group.words.map(word=>word.punctuatedWord).join(" ")},index,group.words.map(word=>word.id)))}
function mergeWorking(directory,record,identity,segments,completedAt){const file=path.join(directory,"transcript","working.json"),previous=fs.existsSync(file)?readJson(file):{schemaVersion:"1.1.0",recordType:"WORKING_TRANSCRIPT",derivedFrom:[],speakerMap:{status:"unreconciled",assignments:[]},segments:[]},next={...previous,schemaVersion:"1.1.0",derivedFrom:[...new Set([...(previous.derivedFrom||[]).filter(item=>item!==identity.sha256),identity.sha256])],segments:[...(previous.segments||[]).filter(item=>item.sourceJobIdentity!==identity.sha256),...segments].sort((a,b)=>(a.sourceOrdinal-b.sourceOrdinal)||((a.start??0)-(b.start??0))),updatedAt:completedAt};const applied=withTranscriptContentHash(applySpeakerAssignments(next));atomic(file,jsonBytes(applied));return applied}
function lockJob(jobDirectory,identity){const file=path.join(jobDirectory,"job.lock");fs.mkdirSync(jobDirectory,{recursive:true});try{fs.writeFileSync(file,JSON.stringify({pid:process.pid,identity,createdAt:new Date().toISOString()}),{flag:"wx"});return()=>fs.rmSync(file,{force:true})}catch(error){if(error.code!=="EEXIST")throw error;let owner=null;try{owner=readJson(file)}catch{owner=null}if(owner?.pid){try{process.kill(owner.pid,0);throw new Error("This transcription job is already processing in another server process.")}catch(check){if(check.message.includes("already processing"))throw check}}fs.rmSync(file,{force:true});return lockJob(jobDirectory,identity)}}
function knownCanonicalSpeakers(canonical){const ids=new Set(["witness","reporter"]);for(const item of canonical?.counsel||[])if(item.id)ids.add(item.id);for(const group of [canonical?.participants?.otherAttendees,canonical?.participants?.interpreters,canonical?.participants?.videographers])for(const item of group||[])if(item.id)ids.add(item.id);return ids}

export function reconcileSpeakerMap(working,assignments,{allowedSpeakerIdentities=null}={}){if(!Array.isArray(assignments))throw new Error("Speaker assignments must be an array.");const seen=new Set(),observed=observedSpeakerKeys(working),normalized=assignments.map(item=>{const sourceJobIdentity=String(item.sourceJobIdentity||"").trim();if(!sourceJobIdentity||!Number.isInteger(item.deepgramSpeaker))throw new Error("Every speaker assignment requires a source job identity and integer Deepgram speaker number.");const key=`${sourceJobIdentity}:${item.deepgramSpeaker}`;if(seen.has(key))throw new Error(`Speaker ${item.deepgramSpeaker} for job ${sourceJobIdentity} has more than one assignment.`);if(!observed.has(key))throw new Error("A speaker assignment does not correspond to an observed Deepgram speaker.");seen.add(key);const speakerIdentity=String(item.speakerIdentity||"").trim(),transcriptRole=String(item.transcriptRole||"").trim();if(!speakerIdentity||!TRANSCRIPT_ROLES.includes(transcriptRole))throw new Error("Every speaker assignment requires a canonical identity and supported transcript role.");if(allowedSpeakerIdentities&&!allowedSpeakerIdentities.has(speakerIdentity))throw new Error(`Speaker identity ${speakerIdentity} is not present in the Canonical Deposition Data Record.`);return{sourceJobIdentity,deepgramSpeaker:item.deepgramSpeaker,speakerIdentity,transcriptRole}});const reconciled=applySpeakerAssignments({...working,speakerMap:{status:"unreconciled",assignments:normalized}},normalized);return{...reconciled,speakerMap:{...reconciled.speakerMap,reconciledAt:new Date().toISOString()},updatedAt:new Date().toISOString()}}
export function reconcileDepositionSpeakers(root,{depositionId,assignments,storageRoot}){const directory=depositionDirectory(root,depositionId,{storageRoot}),file=path.join(directory,"transcript","working.json");if(!fs.existsSync(file))throw new Error("The working transcript has not been created.");const canonical=readJson(path.join(directory,"intake","canonical-deposition-record.json")),reconciled=withTranscriptContentHash(reconcileSpeakerMap(readJson(file),assignments,{allowedSpeakerIdentities:knownCanonicalSpeakers(canonical)}));atomic(file,jsonBytes(reconciled));return reconciled}

function jobPaths(directory,identity){const jobDirectory=path.join(directory,"deepgram","jobs",identity);return{jobDirectory,jobFile:path.join(jobDirectory,"job.json"),requestFile:path.join(jobDirectory,"request.json"),rawFile:path.join(jobDirectory,"raw-response.json"),evidenceFile:path.join(jobDirectory,"asr-evidence.json")}}
function integrity(paths,job){const issues=[];for(const [name,file,expected] of [["request",paths.requestFile,job.request?.sha256],["raw-response",paths.rawFile,job.response?.rawResponseSha256],["asr-evidence",paths.evidenceFile,job.response?.evidenceSha256]]){if(!fs.existsSync(file))issues.push(`${name} is missing`);else if(expected&&hashFile(file)!==expected)issues.push(`${name} hash mismatch`)}return issues}
function rebuildFromRaw(directory,record,job,paths){const rawBytes=fs.readFileSync(paths.rawFile);if(hashFile(paths.rawFile)!==job.response.rawResponseSha256)throw new Error("Stored raw Deepgram response failed integrity verification.");const raw=JSON.parse(rawBytes.toString("utf8")),completedAt=new Date().toISOString(),identity={input:job.identity,sha256:job.jobId},evidence=deriveEvidence(raw,{identity,rawResponseSha256:job.response.rawResponseSha256,deliveredAudio:job.response.deliveredAudio,completedAt}),sourceOrdinal=record.audio.findIndex(item=>item.uploadId===job.uploadId),segments=deriveSegments(raw,evidence,{identity,uploadId:job.uploadId,sourceOrdinal});atomic(paths.evidenceFile,jsonBytes(evidence));job.response.evidenceSha256=hashFile(paths.evidenceFile);job.response.evidencePath=relative(directory,paths.evidenceFile);job.rebuiltAt=completedAt;atomic(paths.jobFile,jsonBytes(job));return{job,evidence,workingTranscript:mergeWorking(directory,record,identity,segments,completedAt)}}

// `force` re-derives from the preserved raw response even when integrity is intact. Changing
// deriveSegments changes the projection but not the evidence hash, so nothing would otherwise
// signal that a stored working.json is stale. It reads raw-response.json off disk and verifies
// its SHA-256 -- no Deepgram call, no cost, and it refuses to run if the bytes do not verify.
export function getTranscriptionJob(root,{depositionId,jobId,storageRoot,rebuild=true,force=false}){const directory=depositionDirectory(root,depositionId,{storageRoot}),record=readJson(path.join(directory,"deposition.json")),paths=jobPaths(directory,jobId);if(!fs.existsSync(paths.jobFile))throw new Error("Transcription job was not found.");const job=readJson(paths.jobFile),issues=integrity(paths,job);if((issues.length||force)&&rebuild&&job.status==="completed"&&fs.existsSync(paths.rawFile)&&hashFile(paths.rawFile)===job.response?.rawResponseSha256&&!issues.some(issue=>issue.startsWith("request")))return{...rebuildFromRaw(directory,record,job,paths),integrity:{valid:true,rebuilt:true,issues}};return{job,evidence:fs.existsSync(paths.evidenceFile)?readJson(paths.evidenceFile):null,workingTranscript:fs.existsSync(path.join(directory,"transcript","working.json"))?readJson(path.join(directory,"transcript","working.json")):null,integrity:{valid:issues.length===0,rebuilt:false,issues}}}
export function listTranscriptionJobs(root,{depositionId,storageRoot}){const directory=depositionDirectory(root,depositionId,{storageRoot}),jobsDirectory=path.join(directory,"deepgram","jobs");if(!fs.existsSync(jobsDirectory))return[];return fs.readdirSync(jobsDirectory,{withFileTypes:true}).filter(item=>item.isDirectory()).map(item=>{try{return readJson(path.join(jobsDirectory,item.name,"job.json"))}catch{return null}}).filter(Boolean).sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt)))}
export function getWorkingTranscript(root,{depositionId,storageRoot}){const directory=depositionDirectory(root,depositionId,{storageRoot}),file=path.join(directory,"transcript","working.json");if(!fs.existsSync(file))throw new Error("The working transcript has not been created.");return readJson(file)}
// Every completed job's asr-evidence.json, for the render join. Read-only: this never rebuilds,
// because a rebuild rewrites working.json and the Workspace must not mutate the record simply
// by being opened.
// The overlay lives beside working.json, never inside it. Reading is tolerant of absence -- a
// deposition with no edits has no overlay file -- and writing is atomic, because a half-written
// operation list would be indistinguishable from a reporter who stopped halfway.
function overlayFile(root,depositionId,storageRoot){return path.join(depositionDirectory(root,depositionId,{storageRoot}),"transcript","reporter-overlay.json")}
export function readReporterOverlay(root,{depositionId,storageRoot}){const file=overlayFile(root,depositionId,storageRoot);return validateOverlay(fs.existsSync(file)?readJson(file):null,depositionId)}
export function writeReporterOverlay(root,{depositionId,storageRoot,overlay}){const validated=validateOverlay(overlay,depositionId);atomic(overlayFile(root,depositionId,storageRoot),jsonBytes(validated));return validated}
export function appendReporterOperations(root,{depositionId,storageRoot,operations}){return writeReporterOverlay(root,{depositionId,storageRoot,overlay:appendOperations(readReporterOverlay(root,{depositionId,storageRoot}),operations)})}
export function undoReporterOperation(root,{depositionId,storageRoot}){const {overlay,removed}=undoLast(readReporterOverlay(root,{depositionId,storageRoot}));return{overlay:writeReporterOverlay(root,{depositionId,storageRoot,overlay}),removed}}

export function readAsrEvidence(root,{depositionId,storageRoot}){const directory=depositionDirectory(root,depositionId,{storageRoot}),jobsDirectory=path.join(directory,"deepgram","jobs");if(!fs.existsSync(jobsDirectory))return[];return fs.readdirSync(jobsDirectory,{withFileTypes:true}).filter(item=>item.isDirectory()).map(item=>{const file=path.join(jobsDirectory,item.name,"asr-evidence.json");try{return fs.existsSync(file)?readJson(file):null}catch{return null}}).filter(Boolean)}
export function getSpeakerCandidates(root,{depositionId,storageRoot}){const directory=depositionDirectory(root,depositionId,{storageRoot}),canonical=readJson(path.join(directory,"intake","canonical-deposition-record.json")),value=field=>String(field?.value??field??"").trim(),candidates=[{id:"witness",label:value(canonical?.deposition?.witness)||"Witness",defaultRole:"WITNESS"},{id:"reporter",label:value(canonical?.reporter?.fullName)||"Court Reporter",defaultRole:"COURT_REPORTER"},...(canonical?.counsel||[]).map(item=>({id:item.id,label:value(item.fullName)||item.id,defaultRole:String(value(item.appearanceRole)||"QUESTIONING_ATTORNEY").toUpperCase().replaceAll(" ","_")})),...(canonical?.participants?.interpreters||[]).map(item=>({id:item.id,label:value(item.fullName||item.name)||item.id,defaultRole:"INTERPRETER"})),...(canonical?.participants?.videographers||[]).map(item=>({id:item.id,label:value(item.fullName||item.name)||item.id,defaultRole:"VIDEOGRAPHER"}))];return{candidates,roles:TRANSCRIPT_ROLES}}

export async function runTranscriptionJob(root,{depositionId,uploadId,keytermOverrideReason="",storageRoot,submit}){if(!depositionId||!uploadId)throw new Error("Deposition ID and upload ID are required.");const directory=depositionDirectory(root,depositionId,{storageRoot}),record=readJson(path.join(directory,"deposition.json")),audio=record.audio?.find(item=>item.uploadId===uploadId);if(!audio)throw new Error("The selected audio is not part of this deposition.");const audioFile=path.resolve(directory,...String(audio.path).split("/"));if(!fs.existsSync(audioFile)||hashFile(audioFile)!==audio.sha256)throw new Error("The frozen deposition audio failed SHA-256 verification.");const intake=readJson(path.join(directory,"intake","intake.json")),keyterms=authoritativeKeyterms(intake,{overrideReason:keytermOverrideReason}),identity=transcriptionIdentity({audioSha256:audio.sha256,rxOperationId:audio.operationId||null,keytermSetSha256:keyterms.sha256}),paths=jobPaths(directory,identity.sha256);
  if(fs.existsSync(paths.jobFile)){const existing=getTranscriptionJob(root,{depositionId,jobId:identity.sha256,storageRoot});if(existing.job.status==="completed"&&existing.integrity.valid)return{cached:true,...existing};if(existing.job.status==="completed")throw new Error(`Stored transcription integrity verification failed: ${existing.integrity.issues.join("; ")}`)}if(ACTIVE_JOBS.has(identity.sha256))throw new Error("This transcription job is already processing.");const unlock=lockJob(paths.jobDirectory,identity.sha256),existing=fs.existsSync(paths.jobFile)?readJson(paths.jobFile):null,attemptNumber=(existing?.attempts||0)+1,attemptDirectory=path.join(paths.jobDirectory,"attempts",String(attemptNumber).padStart(4,"0")),request=buildDeepgramRequest(keyterms.wire),requestArtifact={schemaVersion:"1.1.0",configurationVersion:DEEPGRAM_CONFIGURATION_VERSION,url:request.url,options:request.options,keyterms:request.keyterms,submittedAt:new Date().toISOString(),audioIdentity:identity.input,sourceAudio:{...audio,path:relative(directory,audioFile),bytes:fs.statSync(audioFile).size}},requestBytes=jsonBytes(requestArtifact);atomic(paths.requestFile,requestBytes);atomic(path.join(attemptDirectory,"request.json"),requestBytes);const now=new Date().toISOString(),job={schemaVersion:"1.1.0",jobId:identity.sha256,depositionId,uploadId,status:"processing",identity:identity.input,keyterms:{count:keyterms.wire.length,estimatedTokens:keyterms.estimatedTokens,sha256:keyterms.sha256,overrideReason:keyterms.overrideReason},sourceAudio:audio,request:{path:relative(directory,paths.requestFile),sha256:sha(requestBytes)},attempts:attemptNumber,createdAt:existing?.createdAt||now,startedAt:now,completedAt:null,failure:null};atomic(paths.jobFile,jsonBytes(job));ACTIVE_JOBS.add(identity.sha256);
  try{const result=await submit({audio,audioFile,request,keyterms:keyterms.wire,operationId:identity.sha256});for(const [index,transport] of (result.transportAttempts||[]).entries()){const bytes=transport.rawResponseBytes?Buffer.from(transport.rawResponseBytes):null;if(bytes)atomic(path.join(attemptDirectory,`transport-${index+1}-response.bin`),bytes);atomic(path.join(attemptDirectory,`transport-${index+1}-metadata.json`),jsonBytes({...transport,rawResponseBytes:undefined,rawResponseSha256:bytes?sha(bytes):null}))}const rawBytes=Buffer.from(result.rawResponseBytes??result.rawResponseText,"utf8"),completedAt=new Date().toISOString(),rawHash=sha(rawBytes),deliveredAudio=result.delivery||{source:"deposition-workspace",path:relative(directory,audioFile),sha256:audio.sha256,bytes:fs.statSync(audioFile).size};atomic(paths.rawFile,rawBytes);atomic(path.join(attemptDirectory,"raw-response.json"),rawBytes);atomic(path.join(attemptDirectory,"response-metadata.json"),jsonBytes({status:result.response?.status??200,headers:result.response?.headers||{},receivedAt:completedAt,rawResponseSha256:rawHash,deliveredAudio}));const raw=JSON.parse(rawBytes.toString("utf8")),evidence=deriveEvidence(raw,{identity,rawResponseSha256:rawHash,deliveredAudio,completedAt}),sourceOrdinal=record.audio.findIndex(item=>item.uploadId===uploadId),segments=deriveSegments(raw,evidence,{identity,uploadId,sourceOrdinal});atomic(paths.evidenceFile,jsonBytes(evidence));const workingTranscript=mergeWorking(directory,record,identity,segments,completedAt);Object.assign(job,{status:"completed",completedAt,response:{requestId:raw?.metadata?.request_id||null,httpStatus:result.response?.status??200,rawResponsePath:relative(directory,paths.rawFile),rawResponseSha256:rawHash,evidencePath:relative(directory,paths.evidenceFile),evidenceSha256:hashFile(paths.evidenceFile),deliveredAudio}});atomic(paths.jobFile,jsonBytes(job));return{cached:false,job,evidence,workingTranscript,normalized:result.normalized,integrity:{valid:true,rebuilt:false,issues:[]}}}catch(error){const failedBytes=error?.rawResponseBytes?Buffer.from(error.rawResponseBytes):null;if(failedBytes)atomic(path.join(attemptDirectory,"error-response.bin"),failedBytes);const failure={message:error instanceof Error?error.message:String(error),code:error?.code||null,httpStatus:error?.status||null,rawResponseSha256:failedBytes?sha(failedBytes):null,outcome:error?.code==="TIMEOUT"?"request_outcome_unknown":"failed_response_received"};atomic(path.join(attemptDirectory,"failure.json"),jsonBytes(failure));Object.assign(job,{status:"failed",completedAt:new Date().toISOString(),failure});atomic(paths.jobFile,jsonBytes(job));throw error}finally{ACTIVE_JOBS.delete(identity.sha256);unlock()}}
